force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>UUID</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/infrastructure/persistence/selectors/ContactSelector.cls
public with sharing class ContactSelector {

    public static List<Contact> getByIds(Set<Id> contactIds) {
        List<Contact> contacts = [SELECT Id, Home_Country__c, Product__c FROM Contact WHERE Id IN:contactIds];
        return contacts;
    }

    public static Contact getById(Id contactId) {
        List<Contact> contacts = getByIds(new Set<Id>{contactId});
        return (!contacts.isEmpty()) ? contacts.get(0) : null;
    }

    public static Contact getByUUID(String uuid) {
        List<Contact> contacts = [SELECT Id, ExternalId__c, Product__r.Name, Email, FirstName, LastName, AccountId, Home_Country__c, Product__c FROM Contact WHERE ExternalId__c =:uuid LIMIT 1];
        return (!contacts.isEmpty()) ? contacts.get(0) : null;
    }
}