force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>UUID</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/domain/ContactsTest.cls
@IsTest
private class ContactsTest {

    @IsTest
    public static void whenInsertContact() {

        Contact contact = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            Home_Country__c = 'DE'
        );

        insert contact;
        Test.startTest();
        Contact insertedContact = ContactSelector.getById(contact.Id);

        Assert.isNotNull(insertedContact.ExternalId__c);
        String uuid = insertedContact.ExternalId__c;

        Contact contactByUUID = ContactSelector.getByUUID(uuid);
        Assert.areEqual(insertedContact.Id, contactByUUID.Id);
        Test.stopTest();
    }
}