force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/application/ui/ContactPlanDetailsController.cls
public class ContactPlanDetailsController {
    @AuraEnabled(cacheable=true)
    public static CustomerDetailsDTO getPlanServices(Id recordId) {
        Case caseObject = CaseSelector.getById(recordId);
        // To reduce amount of queries in a potential increase of scope, the pricebookEntries can be retrieve in a subquery in Pricebook query
        Pricebook2 countryPricebook = PricebookSelector.getByCountry(caseObject.Contact.Home_Country__c);
        List<PricebookEntry> pricebookEntries = PricebookEntrySelector.getPlanPricebookEntriesByPricebook(caseObject.Contact.Product__c, countryPricebook.Id);

        return new CustomerDetailMapper(pricebookEntries)
                    .getCustomerPlanDetailsDTO(caseObject.Contact.Product__r.Name, caseObject.Contact.Home_Country__c);
    }
}