force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/infrastructure/persistence/selectors/CaseSelector.cls
public with sharing class CaseSelector {

    public static List<Case> getByIds(Set<Id> caseIds) {
        List<Case> cases = [SELECT ContactId, Contact.Product__c,Contact.Product__r.Name, Contact.Home_Country__c FROM Case WHERE Id IN: caseIds];
        return cases;
    }

    public static Case getById(Id caseId) {
        List<Case> cases = getByIds(new Set<Id>{caseId});
        return (!cases.isEmpty()) ? cases.get(0) : null;
    }
}