force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <default>true</default>
                <label>DE</label>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plan related to a service</description>
    <label>Plan</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Plan.recordType-meta.xml
<RecordType>
    <fullName>Plan</fullName>
    <active>true</active>
    <description>Record Type to for plans</description>
    <label>Plan</label>
</RecordType>

force-app/main/default/classes/tests/application/ui/ContactPlanDetailsControllerTest.cls
@IsTest
private class ContactPlanDetailsControllerTest {

    @TestSetup
    static void setup() {
        Product2 product = new Product2(Name='Metal Plan');
        insert product;

        Product2 serviceProduct = new Product2(Name='ATM Fee', Plan__c=product.Id);
        insert serviceProduct;
        
        Pricebook2 pricebook = new Pricebook2(Name = 'DE Pricebook', Country__c='DE', isActive=true);
        insert pricebook;

        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
        pricebookEntries.add(new PricebookEntry(Pricebook2Id=Test.getStandardPricebookId(), Product2Id = serviceProduct.Id, UnitPrice=0,Fee__c=0));
        pricebookEntries.add(new PricebookEntry(Pricebook2Id=pricebook.Id, Product2Id = serviceProduct.Id, UnitPrice=0,Fee__c=0, isActive=true));
        insert pricebookEntries;

        List<Contact> contacts = new List<Contact>();
        contacts.add(new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            Home_Country__c = 'DE',
            Product__c = product.Id
        ));

        contacts.add(new Contact(
            FirstName = 'John',
            LastName = 'No Country'
        ));

        insert contacts;


        Case caseRecord = new Case(ContactId=contacts[0].id);
        insert caseRecord;
    }

    @IsTest
    static void whenLwcRetrieveCustomerDetail(){
        Case caseRecord = [SELECT Id FROM Case LIMIT 1];
        Test.startTest();
        PlanDetailsDTO planDetails = ContactPlanDetailsController.getPlanServices(caseRecord.Id);
        Assert.areEqual(planDetails.planServices.size(), 1);
        Assert.areEqual(planDetails.planType, 'Metal Plan');
        Test.stopTest();
        
    }
}